---
apiVersion: v1
kind: Secret
metadata:
  name: metal-cloud-config
  namespace: kube-system
stringData:
  cloud-sa.json: |
    {
      "apiKey": "${auth_token}",
      "projectID": "${project_id}",
      "loadbalancer": "kube-vip://"
    }

